### ISSUE TITLE
Implementation of RoPE

### ISSUE THREAD

**Issue by datourat** [Lightning-AI/litgpt#1214]
Is the implementation of RoPE equivalent as the one proposed in the original paper? https://github.com/Lightning-AI/litgpt/blob/main/litgpt/model.py#L377

Based on the Equation (34) in [the original paper](https://arxiv.org/pdf/2104.09864.pdf), we should rotate every two adjacent index, instead of swapping the position of the first half of vector and the second half. Not sure if I missed anything.

**Comment by awaelchli** [comment]
As far as I know, our implementation is supposed to be equivalent to Meta Llama's implementation 

- https://github.com/meta-llama/llama/blob/54c22c0d63a3f3c9e77f43a6a3041c00018f4964/llama/model.py#L100-L104
- https://github.com/meta-llama/llama/blob/54c22c0d63a3f3c9e77f43a6a3041c00018f4964/llama/model.py#L156-L161

The implementation is different because of the license, but should be mathematically equivalent. We have simple parity tests: 
- https://github.com/Lightning-AI/litgpt/blob/main/tests/test_rope.py
- https://github.com/Lightning-AI/litgpt/blob/a509064d802d1e05bab16d9a49e763a6c955b84e/tests/test_model.py#L258-L260

**Comment by datourat** [comment]
I did some research. It looks like there are different variants of RoPE, *GPT-NeoX style* RoPE vs. *GPT-J style* RoPE based on [this](https://github.com/huggingface/transformers/issues/25199#issue-1828682402). Meta Llama seems to implement the *GPT-J style* one, which should be equivalent to the one proposed in [the original paper](https://arxiv.org/pdf/2104.09864.pdf). Not sure which one you really meant to implement.

**Comment by RuABraun** [comment]
They are essentially equivalent. Choosing to pair x_1,x_2 and x_3,x_4 OR x_1,x_{n/2} and x_2,x_{n/2+1} is arbitrary and makes no effective difference but the latter implementation is more efficient.
