### ISSUE TITLE
Thunder test exceeds 5 min timeout

### ISSUE THREAD

**Issue by lantiga** [Lightning-AI/litgpt#1303]
This test has been disabled as it often exceeds the 5 min timeout: https://github.com/Lightning-AI/litgpt/blob/main/tests/test_thunder_fsdp.py#L265

We should investigate keeping it under 5 mins to avoid CI to bloat.

**Comment by Andrei-Aksionov** [comment]
There is another question: why sometimes CI runs faster and sometimes significantly slower.
For example, [this](https://dev.azure.com/Lightning-AI/lit%20Models/_build/results?buildId=199001&view=logs&j=8a08b103-7f3c-5f4b-1889-6a795acbb007) run passed, while [this](https://dev.azure.com/Lightning-AI/lit%20Models/_build/results?buildId=199014&view=logs&j=8a08b103-7f3c-5f4b-1889-6a795acbb007) one didn't due to timeout.
Both were executed today with ~45 minutes in difference. Notice that in the first case all the steps are faster, even dependencies installation.
