### ISSUE TITLE
how to pretrain llama2?

### ISSUE THREAD

**Issue by wen020** [Lightning-AI/litgpt#1418]
We read the pretrain code in this repo and find that the pretrain code is gpt model. how to pretrain llama2?
![image](https://github.com/Lightning-AI/litgpt/assets/54690997/5b39a889-1b2b-4610-af6e-9124ed2c3fcc)

**Comment by fireyanci** [comment]
You can read the tutorials

**Comment by rasbt** [comment]
Actually, the `GPT` here is just a Python class. All other LLMs are very similar to GPT, which is why they are derived from that class in code. To choose the LLM you want to pretrain, check the pretrain tutorials here: https://github.com/Lightning-AI/litgpt/blob/main/tutorials/pretrain.md

E.g., `litgpt pretrain ...  --model_name Llama-2-7b-hf ...`

**Comment by wen020** [comment]
ok

**Comment by rasbt** [comment]
I hope this helped. Please feel free to reopen if you have a follow up question.
