### ISSUE TITLE
Liger Kernel Integration

### ISSUE THREAD

**Issue by ByronHsu** [Lightning-AI/litgpt#1703]
Liger (Linkedin GPU Efficient Runtime) Kernel is a collection of Triton kernels designed specifically for LLM training. It can effectively increase multi-GPU training throughput by 20% and reduces memory usage by 60%. We have implemented Hugging Face Compatible RMSNorm, RoPE, SwiGLU, CrossEntropy, FusedLinearCrossEntropy, and more to come. The kernel works out of the box with [Flash Attention](https://github.com/Dao-AILab/flash-attention), [PyTorch FSDP](https://pytorch.org/tutorials/intermediate/FSDP_tutorial.html), and [Microsoft DeepSpeed](https://github.com/microsoft/DeepSpeed). We welcome contributions from the community to gather the best kernels for LLM training.

We are excited to integrate with litgpt and ask for volunteers here! 

Related issue: https://github.com/linkedin/Liger-Kernel/issues/139

**Comment by merryHunter** [comment]
I quickly replaced 2 lines for RMSNorm in `config.py` for toy example of lora finetuning and even on a single RTX 4090 I see a speedup, so it's definitely worth exploring. The problem I see is that litgpt does not directly use transformers and has own blocks for loading weight, which may require more work than a simple monkey patch... but better authors provide their feedback on this.

Lines I replaced:
```
from litgpt.model import RMSNorm
return partial(RMSNorm, add_unit_offset="Gemma" in self.name)
```
with
```
from liger_kernel.transformers.rms_norm import LigerRMSNorm
return partial(LigerRMSNorm)
```

**Comment by ByronHsu** [comment]
Great! We do want to add a litgpt/ interface under our repo https://github.com/linkedin/Liger-Kernel/tree/main/src/liger_kernel given the popularity of litgpt.

**Comment by merryHunter** [comment]
@ByronHsu I did some investigation and seems some of liger kernels are already being integrated through Lightning Thunder, see [https://github.com/Lightning-AI/lightning-thunder/pull/1105] (url). Similarly for RoPE. What concerns RMSNorm, there have to be refactoring done in litgpt, otherwise it throws errors due to current code design in case of monkey patching. So, I would rather expect Thunder to be more intergrated / aligned with Liger Kernel

**Comment by deeptimhe** [comment]
Looking forward to the integration!

**Comment by rasbt** [comment]
Thanks for raising that! I just spoke to some of my colleagues, and we will offer the integration through Thunder (as @merryHunter  mentioned); so in that case, LitGPT doesn't need to be updated directly. I am closing it now here since it's being addressed over in Thunder, but I appreciate the note, and I am looking forward to the integration!
