### ISSUE TITLE
Nothing working…

### ISSUE THREAD

**Issue by degen2** [Lightning-AI/litgpt#1888]
### Bug description

Pure garbage. I tried to load 3 different models on 2 different machines (linux, mac) and not a single one worked out of the box…issues with litdata, Nonetype bla bla bla. Annoying as hell.

### What operating system are you using?

Unknown

### LitGPT Version

``` 



```

**Comment by Andrei-Aksionov** [comment]
Hello @degen2 

It would be nice if you could provide examples of commands that you tried to run and what error messages did you get (with a full stack trace).

Meanwhile, are you sure that the problem is not on your side, i.e. did you use a clean virtual environment to install LitGPT?

One of the options is to use a fresh [Studios](https://lightning.ai/), or you can even reuse this [Studio template](https://lightning.ai/lightning-ai/studios/litgpt-quick-start?view=org&section=featured).

If you want to use your local machine, please check this [tutorial](../blob/main/tutorials/0_to_litgpt.md) and make sure that you've done all the steps from it.
