### ISSUE TITLE
Improved error checking for tokenization mismatch

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/litgpt#471]
PR #465 is introducing error checking when a user attempts to train a model with a mismatched tokenization. This is a great idea and will reduce the headache from confusing failures in the middle of training. 

However, the approach to this can further be improved. 
1) The check in #465 must happen on every batch since it compares the token indices with the vocab size. This is achieved by either iterationg over the entire dataset at the beginning or doing the check every training iteration. Both approaches seem exhaustive. 
2) The check is not 100% fool-proof. One could use two different tokenizations with the same vocab size, running into issues when finetuning and the check in #465 won't catch it. Although granted, given our current models that is rare unless the user has their own models. 

An alternative approach that improves on the two points above would be to

1. Save a metadata file or a metadata dict inside the data file after preprocessing
2. Load the metadata file once at the beginning, validate it matches the tokenizer/model about to be used in that training script (is this meta information readily available?)

**If not enough information is available or the check is too complex however, we should probably not do this.**

**Comment by rasbt** [comment]
Great idea. Yes, the other proposal is more of a quick fix based on a heuristic. A lot of newcomers have issues related to that, so I thought that having something asap is probably most important.

A check based on metadata would of course be even better. Not sure what this metadata would be, but I wouldn't make it filename dependent or so. Because there could actually be some cases where you can share data between models since they use a similar tokenizer. 

For the most thorough check, maybe we could attach the tokenizer's vocabulary to the dataset files? I.e., `tokenizer.processor.get_vocab()`? It should only be 2-5 Mb depending on the tokenizer. Then, in the finetuning script, we can check if the tokenizer there uses the same vocabulary as the tokenizer that was saved in the dataset file. Even if this dictionary has 50k entries or so, this should only take a few seconds max.

**Comment by carmocca** [comment]
Remember that this is meant to be simple scripts, not a framework. If validating this reliably is too cumbersome, we shouldn't add this complexity to the code.

**Comment by awaelchli** [comment]
Agreed and why the last sentence of the issue description is in bold 😄 
I opened this alternative because I believe #465 is having too heavy of an impact on the scripts.

**Comment by awaelchli** [comment]
This should be solved now.
1. We save the tokenizer configuration to the checkpoint
2. Tokenization happens on the fly for in-memory datasets and the tokenizer gets loaded from the checkpoint.

A mismatch can now only happen if the user manipulates the tokenizer files in the checkpoint, but at this point I think this is out of scope for lit-gpt to detect upfront.
